# WARNING: 本软件仅供演示使用。
# 本仓库的数据库密码声明放在了此文件中，且已经加入了 git 仓库，如不注意可能会造成数据库密码泄露。
# 在生产环境中，你应该把这个文件加入 .gitignore 中，在部署时手动填写。或者将敏感数据放到外部文件中，然后使用 env_file 参数导入。

version: "3.7"
services:
  docker-demo:
    image: docker-demo:3
    environment:
      - FLASK_ENV=production
      - DATABASE_URI=mysql+mysqlconnector://root:foopassword@mysqld/docker_demo?charset=utf8 # WARNING: You should change it!
    ports:
      - "5000:5000"
    volumes:
      - ./log:/docker-demo/log
  mysqld:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=foopassword # WARNING: You should change it!
      - MYSQL_DATABASE=docker_demo
    volumes:
      - ./data:/var/lib/mysql
